public with sharing class Constants {

    public static final Integer NUMBER_OF_DICE = 5;
    public static final Integer UPPER_SECTION_BONUS = 35;
    public static final Integer UPPER_SECTION_BONUS_THRESHOLD = 63;
    public static final Integer FULL_HOUSE = 25;
    public static final Integer SMALL_STRAIGHT = 30;
    public static final Integer LARGE_STRAIGHT = 40;
    public static final Integer YAHTZEE = 50;
    public static final Integer YAHTZEE_BONUS = 100;

}